[package]
name = "esruntime-sdk"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
serde_core = "1.0.228"
serde_json = "1.0.145"
umadb-client = "0.1.29"
umadb-dcb = "0.1.29"

[dev-dependencies]
serde = { version = "1.0", features = ["derive"] }
